name: Deploy to Google Cloud Functions

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2

      - name: Setup gcloud CLI
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Deploy syncShopify
        run: |
          gcloud functions deploy syncShopify --region=us-central1 --gen2 --runtime python311 --source=cloudfunctions/syncShopify --entry-point=syncShopify --trigger-http --allow-unauthenticated

      - name: Deploy strategyLoop
        run: |
          gcloud functions deploy strategyLoop --region=us-central1 --gen2 --runtime python311 --source=cloudfunctions/strategyLoop --entry-point=strategyLoop --trigger-http --allow-unauthenticated